### ISSUE TITLE
cli not found @ 0.1.6

### ISSUE THREAD

**Issue by dbtek** [wittydeveloper/react-apollo-form#16]
/bin/sh: react-apollo-form: command not found

**Comment by wittydeveloper** [comment]
Hi @dbtek ,

Can you give me more context?
Is this an error after running an `npm` command?


What is your target? 
Are you using it from a TypeScript / ES5 / ES6 environment?

Cheers,

**Comment by dbtek** [comment]
Hi @wittydeveloper, sorry for quick issue without details.
In ES6 env, package.json script just like in docs. Using yarn also.

**Comment by wittydeveloper** [comment]
try the following:

```json
{
    "scripts": {
        "react-apollo-form": "yarn run react-apollo-form fetch-mutations <graphql_endpoint> <outpurDir>"
    }
}
```

**Comment by dbtek** [comment]
It's related to yarn. Switching to npm worked for me.

17 Ağu 2018 Cum 17:23 tarihinde kozy <notifications@github.com> şunu yazdı:

**Comment by JMGonzalezR** [comment]
I have the same error with npm 

react-apollo-form\dist\lib\cli.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory,
