### ISSUE TITLE
 Question: Integration with react-jsonschema-form-conditionals

### ISSUE THREAD

**Issue by d4hines** [wittydeveloper/react-apollo-form#19]
Hello,
This looks like an amazing library. Would it be possible to integrate it with [react-json-schema-form-conditionals](https://github.com/RxNT/react-jsonschema-form-conditionals)? Seems like it shouldn't be too bad, but I haven't yet delved into the implementation of either your library or theirs to be sure.

Many thanks!

**Comment by wittydeveloper** [comment]
Hi @d4hines,

I tried to use the project but the default build seems to be broken...
That apart, the API of `react-json-schema-form-conditionals` is really complex and do not leverage Developer eXperience, while the main goal of `react-apollo-form` is to provide a simple API to build forms.

I keep this ticket open for tracking but it's unlikely that this project is gonna to integrate with `react-jsonschema-form-conditionals`.

Thanks for your proposal,

**Comment by wittydeveloper** [comment]
Hi @d4hines,

`react-apollo-form` has been full rewritten for a new library: https://frontier-forms.dev

In term of design choices, Frontier relies on render-props pattern when it comes to have conditional forms.

More, `Frontier` doesn't rely on `react-jsonschema-form`.

I highly appreciate your proposal and I am sorry that it doesn't fit the stack and design choices of `Frontier`.
