### ISSUE TITLE
IMPORTANT: react-apollo-form full rewrite on-going

### ISSUE THREAD

**Issue by wittydeveloper** [wittydeveloper/react-apollo-form#31]
Regarding the current state of the library and the growing demand on it, the `react-apollo-form` is currently under a "re-design" phase.

This may imply some upcoming breaking changes needed to stabilise the library.

We will keep you updated on this ticket.

**Comment by snirp** [comment]
Any updates on the current status?

**Comment by wittydeveloper** [comment]
Hi @snirp ! 
Thanks for your interest! 

Yes there is, here is the timeline for the "redesign" of react-apollo-form that will br called formidable-forms:

- End of February: Design phase finished
- End of March: Implementation phase finished
- April: First release + building some community materials (code-sandbox, doc site, ...)
- April: Support for 2 famous UI-kit (ex: Semantic UI and Material UI)

**Comment by lukasluecke** [comment]
@wittydeveloper Thanks for the update and your work on redesigning this library! I just implemented the current version in a project anyway, with some minor changes - but I'll gladly try and use the new one once it's available 👍 

Will there still be a "dependency" on the apollo codegen in the new version, or will you get all the required information directly?

**Comment by wittydeveloper** [comment]
Hi @lukasluecke,

Thanks for your support. 🙇 

The rewrite will also benefit of a renaming of the library: `Frontier forms`.
The idea of the rewrite is to separate the library into many meaningful pieces in order to make it more powerful, this include:
- support many flavours: `React`, `React Native`, `Vue.js` and `Angular`
- support for many data schema: `GraphQL` and `Swagger`
- also, ui-kits packages for: `Material UI`, `Bootstrap`, `Semantic UI`

Regarding the `GraphQL` part, we will propose 2 ways to use it:
- runtime introspection using `ApolloClient` (better for development mode)
- static generation using `apollo-codegen` (more suitable for production)

the `frontier-forms-graphql` will have a `peerDependencies`  on `apollo` (client + codegen).

Does this answer your question?

**Comment by wittydeveloper** [comment]
**For all question regarding future Migration from `react-apollo-form` to `frontier-forms`, please give a look at https://github.com/wittydeveloper/react-apollo-form/issues/33.**

**Comment by lukasluecke** [comment]
@wittydeveloper 

Thank you for your detailed reply. Yes, that answers my question 🙂

And the reason I asked about the apollo codegen is that I am using [graphql-code-generator](https://github.com/dotansimha/graphql-code-generator) for my codegen needs (generates "nicer" types in my experience, and also more than the apollo codegen, e.g. Hooks for queries and mutations - [react-apollo-hooks](https://github.com/trojanowski/react-apollo-hooks)), and to use their JSON introspection result with your library I had to modify the parsing (the only difference is, that it's not nested under a `data` key). Maybe you can keep that in mind, and make it easy to customize this part 😉

**Comment by EricsG95** [comment]
> Hi @lukasluecke,
> 
> Thanks for your support. 🙇
> 
> The rewrite will also benefit of a renaming of the library: `Frontier forms`.
> The idea of the rewrite is to separate the library into many meaningful pieces in order to make it more powerful, this include:
> 
> * support many flavours: `React`, `React Native`, `Vue.js` and `Angular`
> * support for many data schema: `GraphQL` and `Swagger`
> * also, ui-kits packages for: `Material UI`, `Bootstrap`, `Semantic UI`
> 
> Regarding the `GraphQL` part, we will propose 2 ways to use it:
> 
> * runtime introspection using `ApolloClient` (better for development mode)
> * static generation using `apollo-codegen` (more suitable for production)
> 
> the `frontier-forms-graphql` will have a `peerDependencies` on `apollo` (client + codegen).
> 
> Does this answer your question?

Wow I will be totally looking for the full support with Angular in the future. However what is the current library state with Angular itself?

**Comment by wittydeveloper** [comment]
Hi everybody,

The development of `<Frontier />` is now finished for the first `0.1.0` RC: https://github.com/frontier-forms/frontier-forms

Please know that I'll work on a migration or compatibility with `react-apollo-form` in the upcoming weeks.
This migration part will be the subject of another ticket.

Feel free to leave comments on https://github.com/frontier-forms/frontier-forms/issues.

**Comment by wittydeveloper** [comment]
Hi @EricsG95,

For now `Frontier` only support React.
I'll soon start to look for contributors for the Angular support. 👀 

Stay tuned on https://github.com/frontier-forms/frontier-forms
